<!DOCTYPE html>
<html class="writer-html5" lang="zh-CN/html" >
<head>
  <meta charset="utf-8" /><meta name="generator" content="Docutils 0.18.1: http://docutils.sourceforge.net/" />

  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Creating a part &mdash; abqpy 2016.5.7 文档</title>
      <link rel="stylesheet" href="../../../_static/pygments.css" type="text/css" />
      <link rel="stylesheet" href="../../../_static/css/theme.css" type="text/css" />
      <link rel="stylesheet" href="../../../_static/togglebutton.css" type="text/css" />
      <link rel="stylesheet" href="../../../_static/copybutton.css" type="text/css" />
      <link rel="stylesheet" href="../../../_static/sphinx-codeautolink.css" type="text/css" />
      <link rel="stylesheet" href="../../../_static/css/tooltipster.custom.css" type="text/css" />
      <link rel="stylesheet" href="../../../_static/css/tooltipster.bundle.min.css" type="text/css" />
      <link rel="stylesheet" href="../../../_static/css/tooltipster-sideTip-shadow.min.css" type="text/css" />
      <link rel="stylesheet" href="../../../_static/css/tooltipster-sideTip-punk.min.css" type="text/css" />
      <link rel="stylesheet" href="../../../_static/css/tooltipster-sideTip-noir.min.css" type="text/css" />
      <link rel="stylesheet" href="../../../_static/css/tooltipster-sideTip-light.min.css" type="text/css" />
      <link rel="stylesheet" href="../../../_static/css/tooltipster-sideTip-borderless.min.css" type="text/css" />
      <link rel="stylesheet" href="../../../_static/css/micromodal.css" type="text/css" />
      <link rel="stylesheet" href="../../../_static/graphviz.css" type="text/css" />
      <link rel="stylesheet" href="../../../_static/sg_gallery.css" type="text/css" />
      <link rel="stylesheet" href="../../../_static/sg_gallery-binder.css" type="text/css" />
      <link rel="stylesheet" href="../../../_static/sg_gallery-dataframe.css" type="text/css" />
      <link rel="stylesheet" href="../../../_static/sg_gallery-rendered-html.css" type="text/css" />
      <link rel="stylesheet" href="../../../_static/autoclasstoc.css" type="text/css" />
      <link rel="stylesheet" href="../../../_static/css/sphinx_rtd_theme.css" type="text/css" />
      <link rel="stylesheet" href="../../../_static/design-style.1e8bd061cd6da7fc9cf755528e8ffc24.min.css" type="text/css" />
  <!--[if lt IE 9]>
    <script src="../../../_static/js/html5shiv.min.js"></script>
  <![endif]-->
  
        <script src="../../../_static/jquery.js"></script>
        <script src="../../../_static/_sphinx_javascript_frameworks_compat.js"></script>
        <script data-url_root="../../../" id="documentation_options" src="../../../_static/documentation_options.js"></script>
        <script src="../../../_static/doctools.js"></script>
        <script src="../../../_static/sphinx_highlight.js"></script>
        <script src="../../../_static/clipboard.min.js"></script>
        <script src="../../../_static/copybutton.js"></script>
        <script src="../../../_static/js/hoverxref.js"></script>
        <script src="../../../_static/js/tooltipster.bundle.min.js"></script>
        <script src="../../../_static/js/micromodal.min.js"></script>
        <script>let toggleHintShow = 'Click to show';</script>
        <script>let toggleHintHide = 'Click to hide';</script>
        <script>let toggleOpenOnPrint = 'true';</script>
        <script src="../../../_static/togglebutton.js"></script>
        <script kind="utterances">

    var commentsRunWhenDOMLoaded = cb => {
    if (document.readyState != 'loading') {
        cb()
    } else if (document.addEventListener) {
        document.addEventListener('DOMContentLoaded', cb)
    } else {
        document.attachEvent('onreadystatechange', function() {
        if (document.readyState == 'complete') cb()
        })
    }
}

var addUtterances = () => {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src = "https://utteranc.es/client.js";
    script.async = "async";

    script.setAttribute("repo", "haiiliin/abqpy");
    script.setAttribute("issue-term", "pathname");
    script.setAttribute("theme", "github-light");
    script.setAttribute("label", "💬 comment");
    script.setAttribute("crossorigin", "anonymous");

    sections = document.querySelectorAll("div.section");
    if (sections !== null) {
        section = sections[sections.length-1];
        section.appendChild(script);
    }
}
commentsRunWhenDOMLoaded(addUtterances);
</script>
        <script>var togglebuttonSelector = '.toggle, .admonition.dropdown';</script>
        <script src="../../../_static/design-tabs.js"></script>
        <script async="async" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
    <script src="../../../_static/js/theme.js"></script>
    <link rel="index" title="索引" href="../../../genindex.html" />
    <link rel="search" title="搜索" href="../../../search.html" />
    <link rel="next" title="Reading from an output database" href="read-output.html" />
    <link rel="prev" title="Simple examples" href="index.html" /> 
</head>

<body class="wy-body-for-nav"> 
  <div class="wy-grid-for-nav">
    <nav data-toggle="wy-nav-shift" class="wy-nav-side">
      <div class="wy-side-scroll">
        <div class="wy-side-nav-search" >

          
          
          <a href="../../../index.html" class="icon icon-home">
            abqpy
          </a>
              <div class="version">
                2016
              </div>
<div role="search">
  <form id="rtd-search-form" class="wy-form" action="../../../search.html" method="get">
    <input type="text" name="q" placeholder="搜索文档" aria-label="搜索文档" />
    <input type="hidden" name="check_keywords" value="yes" />
    <input type="hidden" name="area" value="default" />
  </form>
</div>
        </div><div class="wy-menu wy-menu-vertical" data-spy="affix" role="navigation" aria-label="导航菜单">
              <p class="caption" role="heading"><span class="caption-text">User Manual</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="../../../getting_started.html">Getting Started</a></li>
<li class="toctree-l1"><a class="reference internal" href="../../../envvars.html">Environment Variables</a></li>
<li class="toctree-l1"><a class="reference internal" href="../../../cli.html">Command Line Interface</a></li>
</ul>
<p class="caption" role="heading"><span class="caption-text">Tutorials &amp; Examples</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="../../../tutorials.html">Tutorials</a></li>
<li class="toctree-l1"><a class="reference internal" href="../../../examples/index.html">Examples</a></li>
</ul>
<p class="caption" role="heading"><span class="caption-text">References</span></p>
<ul class="current">
<li class="toctree-l1 current"><a class="reference internal" href="../../index.html">Abaqus Scripting User's Guide</a><ul class="current">
<li class="toctree-l2 current"><a class="reference internal" href="../index.html">About the Abaqus Scripting Interface</a><ul class="current">
<li class="toctree-l3"><a class="reference internal" href="../interface.html">Abaqus/CAE and the Abaqus Scripting Interface</a></li>
<li class="toctree-l3"><a class="reference internal" href="../interact.html">How does the Abaqus Scripting Interface interact with Abaqus/CAE?</a></li>
<li class="toctree-l3 current"><a class="reference internal" href="index.html">Simple examples</a><ul class="current">
<li class="toctree-l4 current"><a class="current reference internal" href="#">Creating a part</a></li>
<li class="toctree-l4"><a class="reference internal" href="read-output.html">Reading from an output database</a></li>
<li class="toctree-l4"><a class="reference internal" href="summary.html">Summary</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="../../python/index.html">Using the Abaqus Scripting Interface</a></li>
<li class="toctree-l2"><a class="reference internal" href="../../environment/index.html">The Abaqus Python Development Environment</a></li>
<li class="toctree-l2"><a class="reference internal" href="../../examples/index.html">Putting it all Together: Abaqus Scripting Interface Examples</a></li>
<li class="toctree-l2"><a class="reference internal" href="../../output/index.html">Accessing an Output Database</a></li>
</ul>
</li>
<li class="toctree-l1"><a class="reference internal" href="../../../reference/index.html">Abaqus Class References</a></li>
<li class="toctree-l1"><a class="reference internal" href="../../../CHANGES.html">Abaqus API Changes</a></li>
<li class="toctree-l1"><a class="reference internal" href="../../../autoapi/index.html">Abqpy API Reference</a></li>
<li class="toctree-l1"><a class="reference internal" href="../../../localization.html">Documentation Localization</a></li>
</ul>
<p class="caption" role="heading"><span class="caption-text">Project Links</span></p>
<ul>
<li class="toctree-l1"><a class="reference external" href="https://github.com/haiiliin/abqpy">GitHub</a></li>
<li class="toctree-l1"><a class="reference external" href="https://pypi.org/project/abqpy">PyPI</a></li>
<li class="toctree-l1"><a class="reference external" href="https://readthedocs.org/projects/abqpy">Read the Docs</a></li>
<li class="toctree-l1"><a class="reference external" href="https://github.com/haiiliin/abqpy/issues">Bug Report</a></li>
</ul>
<p class="caption" role="heading"><span class="caption-text">External Links</span></p>
<ul>
<li class="toctree-l1"><a class="reference external" href="https://www.3ds.com/">Dassault Systèmes</a></li>
<li class="toctree-l1"><a class="reference external" href="https://help.3ds.com/2023/English/DSSIMULIA_Established/SIMULIA_Established_FrontmatterMap/DSDocHome.htm?contextscope=all">SIMULA User Assistance</a></li>
<li class="toctree-l1"><a class="reference external" href="https://www.3ds.com/products-services/simulia/products/abaqus/">Abaqus FEA</a></li>
</ul>
<p class="caption" role="heading"><span class="caption-text">Policy &amp; License</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="../../../policy.html">Comment Policy</a></li>
</ul>

        </div>
      </div>
    </nav>

    <section data-toggle="wy-nav-shift" class="wy-nav-content-wrap"><nav class="wy-nav-top" aria-label="移动版导航菜单" >
          <i data-toggle="wy-nav-top" class="fa fa-bars"></i>
          <a href="../../../index.html">abqpy</a>
      </nav>

      <div class="wy-nav-content">
        <div class="rst-content">
          <div role="navigation" aria-label="页面导航">
  <ul class="wy-breadcrumbs">
      <li><a href="../../../index.html" class="icon icon-home" aria-label="Home"></a></li>
          <li class="breadcrumb-item"><a href="../../index.html">Abaqus Scripting User's Guide</a></li>
          <li class="breadcrumb-item"><a href="../index.html">About the Abaqus Scripting Interface</a></li>
          <li class="breadcrumb-item"><a href="index.html">Simple examples</a></li>
      <li class="breadcrumb-item active">Creating a part</li>
      <li class="wy-breadcrumbs-aside">
            <a href="../../../_sources/user/about/examples/create-part.md.txt" rel="nofollow"> 查看页面源码</a>
      </li>
  </ul>
  <hr/>
</div>
          <div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/Article">
           <div itemprop="articleBody">
             
  <section id="creating-a-part">
<h1>Creating a part<a class="headerlink" href="#creating-a-part" title="此标题的永久链接"></a></h1>
<p>This section includes an example that shows how you can use an Abaqus/CAE script to replicate the functionality of Abaqus/CAE.</p>
<section id="the-example-script">
<h2>The example script<a class="headerlink" href="#the-example-script" title="此标题的永久链接"></a></h2>
<p>This example shows how you can use an Abaqus/CAE script to replicate the functionality of Abaqus/CAE.</p>
<p>The script does the following:</p>
<ul class="simple">
<li><p>Creates a new model in the model database.</p></li>
<li><p>Creates a two-dimensional sketch.</p></li>
<li><p>Creates a three-dimensional, deformable part.</p></li>
<li><p>Extrudes the two-dimensional sketch to create the first geometric feature of the part.</p></li>
<li><p>Creates a new viewport.</p></li>
<li><p>Displays a shaded image of the new part in the new viewport.</p></li>
</ul>
<p>The new viewport and the shaded part are shown in <a class="hxr-hoverxref hxr-tooltip reference internal" href="#cmd-int-aexample-nls"><span class="std std-numref">图 5</span></a>.</p>
<figure class="align-center" id="id1">
<span id="cmd-int-aexample-nls"></span><a class="reference internal image-reference" href="../../../_images/cmd-int-aexample-nls.png"><img alt="../../../_images/cmd-int-aexample-nls.png" src="../../../_images/cmd-int-aexample-nls.png" style="width: 50%;" /></a>
<figcaption>
<p><span class="caption-number">图 5 </span><span class="caption-text">The example creates a new viewport and a part.</span><a class="headerlink" href="#id1" title="此图像的永久链接"></a></p>
</figcaption>
</figure>
<p>The example scripts from this guide can be copied to the user's working directory by using the Abaqus fetch utility:</p>
<div class="highlight-sh notranslate"><div class="highlight"><pre><span></span>abaqus<span class="w"> </span>fetch<span class="w"> </span><span class="nv">job</span><span class="o">=</span>scriptName
</pre></div>
</div>
<p>where scriptName.py is the name of the script (see <a class="reference external" href="https://help.3ds.com/2021/english/dssimulia_established/SIMACAEEXCRefMap/simaexc-c-fetchproc.htm?contextscope=all?">Fetching sample input files</a>). Use the following command to retrieve the script for this example:</p>
<div class="highlight-sh notranslate"><div class="highlight"><pre><span></span>abaqus<span class="w"> </span>fetch<span class="w"> </span><span class="nv">job</span><span class="o">=</span>modelAExample
</pre></div>
</div>
<div class="admonition note">
<p class="admonition-title">备注</p>
<p>Abaqus does not install the sample scripts by default during the installation procedure. As a result, if the Abaqus fetch utility fails to find the sample script, the script may be missing from your Abaqus installation. You must rerun the installation procedure and request Abaqus sample problems from the list of items to install.</p>
</div>
<p>To run the program, do the following:</p>
<ol class="arabic simple">
<li><p>Start Abaqus/CAE by typing abaqus cae.</p></li>
<li><p>From the startup screen, select Run Script.</p></li>
<li><p>From the Run Script dialog box that appears, select modelAExample.py.</p></li>
<li><p>Click OK to run the script.</p></li>
</ol>
<div class="admonition note">
<p class="admonition-title">备注</p>
<p>If Abaqus/CAE is already running, you can run the script by selecting from the main menu bar.</p>
</div>
<p>The example follows:</p>
<div class="highlight-python2 notranslate"><div class="highlight"><pre><span></span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">modelAExample.py</span>

<span class="sd">A simple example: Creating a part.</span>
<span class="sd">&quot;&quot;&quot;</span>

<span class="kn">from</span> <span class="nn">abaqus</span> <span class="kn">import</span> <span class="o">*</span>
<span class="kn">from</span> <span class="nn">abaqusConstants</span> <span class="kn">import</span> <span class="o">*</span>
<span class="n">backwardCompatibility</span><span class="o">.</span><span class="n">setValues</span><span class="p">(</span><span class="n">includeDeprecated</span><span class="o">=</span><span class="bp">True</span><span class="p">,</span> <span class="n">reportDeprecated</span><span class="o">=</span><span class="bp">False</span><span class="p">)</span>

<span class="kn">import</span> <span class="nn">sketch</span>
<span class="kn">import</span> <span class="nn">part</span>

<span class="n">myModel</span> <span class="o">=</span> <span class="n">mdb</span><span class="o">.</span><span class="n">Model</span><span class="p">(</span><span class="n">name</span><span class="o">=</span><span class="s1">&#39;Model A&#39;</span><span class="p">)</span>

<span class="n">mySketch</span> <span class="o">=</span> <span class="n">myModel</span><span class="o">.</span><span class="n">ConstrainedSketch</span><span class="p">(</span><span class="n">name</span><span class="o">=</span><span class="s1">&#39;Sketch A&#39;</span><span class="p">,</span> <span class="n">sheetSize</span><span class="o">=</span><span class="mf">200.0</span><span class="p">)</span>

<span class="n">xyCoordsInner</span> <span class="o">=</span> <span class="p">((</span><span class="o">-</span><span class="mi">5</span> <span class="p">,</span> <span class="mi">20</span><span class="p">),</span> <span class="p">(</span><span class="mi">5</span><span class="p">,</span> <span class="mi">20</span><span class="p">),</span> <span class="p">(</span><span class="mi">15</span><span class="p">,</span> <span class="mi">0</span><span class="p">),</span> <span class="p">(</span><span class="o">-</span><span class="mi">15</span><span class="p">,</span> <span class="mi">0</span><span class="p">),</span> <span class="p">(</span><span class="o">-</span><span class="mi">5</span><span class="p">,</span> <span class="mi">20</span><span class="p">))</span>

<span class="n">xyCoordsOuter</span> <span class="o">=</span> <span class="p">((</span><span class="o">-</span><span class="mi">10</span><span class="p">,</span> <span class="mi">30</span><span class="p">),</span> <span class="p">(</span><span class="mi">10</span><span class="p">,</span> <span class="mi">30</span><span class="p">),</span> <span class="p">(</span><span class="mi">40</span><span class="p">,</span> <span class="o">-</span><span class="mi">30</span><span class="p">),</span>
    <span class="p">(</span><span class="mi">30</span><span class="p">,</span> <span class="o">-</span><span class="mi">30</span><span class="p">),</span> <span class="p">(</span><span class="mi">20</span><span class="p">,</span> <span class="o">-</span><span class="mi">10</span><span class="p">),</span> <span class="p">(</span><span class="o">-</span><span class="mi">20</span><span class="p">,</span> <span class="o">-</span><span class="mi">10</span><span class="p">),</span>
    <span class="p">(</span><span class="o">-</span><span class="mi">30</span><span class="p">,</span> <span class="o">-</span><span class="mi">30</span><span class="p">),</span> <span class="p">(</span><span class="o">-</span><span class="mi">40</span><span class="p">,</span> <span class="o">-</span><span class="mi">30</span><span class="p">),</span> <span class="p">(</span><span class="o">-</span><span class="mi">10</span><span class="p">,</span> <span class="mi">30</span><span class="p">))</span>

<span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="nb">len</span><span class="p">(</span><span class="n">xyCoordsInner</span><span class="p">)</span><span class="o">-</span><span class="mi">1</span><span class="p">):</span>
    <span class="n">mySketch</span><span class="o">.</span><span class="n">Line</span><span class="p">(</span><span class="n">point1</span><span class="o">=</span><span class="n">xyCoordsInner</span><span class="p">[</span><span class="n">i</span><span class="p">],</span>
        <span class="n">point2</span><span class="o">=</span><span class="n">xyCoordsInner</span><span class="p">[</span><span class="n">i</span><span class="o">+</span><span class="mi">1</span><span class="p">])</span>

<span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="nb">len</span><span class="p">(</span><span class="n">xyCoordsOuter</span><span class="p">)</span><span class="o">-</span><span class="mi">1</span><span class="p">):</span>
    <span class="n">mySketch</span><span class="o">.</span><span class="n">Line</span><span class="p">(</span><span class="n">point1</span><span class="o">=</span><span class="n">xyCoordsOuter</span><span class="p">[</span><span class="n">i</span><span class="p">],</span>
        <span class="n">point2</span><span class="o">=</span><span class="n">xyCoordsOuter</span><span class="p">[</span><span class="n">i</span><span class="o">+</span><span class="mi">1</span><span class="p">])</span>

<span class="n">myPart</span> <span class="o">=</span> <span class="n">myModel</span><span class="o">.</span><span class="n">Part</span><span class="p">(</span><span class="n">name</span><span class="o">=</span><span class="s1">&#39;Part A&#39;</span><span class="p">,</span> <span class="n">dimensionality</span><span class="o">=</span><span class="n">THREE_D</span><span class="p">,</span>
    <span class="nb">type</span><span class="o">=</span><span class="n">DEFORMABLE_BODY</span><span class="p">)</span>

<span class="n">myPart</span><span class="o">.</span><span class="n">BaseSolidExtrude</span><span class="p">(</span><span class="n">sketch</span><span class="o">=</span><span class="n">mySketch</span><span class="p">,</span> <span class="n">depth</span><span class="o">=</span><span class="mf">20.0</span><span class="p">)</span>

<span class="n">myViewport</span> <span class="o">=</span> <span class="n">session</span><span class="o">.</span><span class="n">Viewport</span><span class="p">(</span><span class="n">name</span><span class="o">=</span><span class="s1">&#39;Viewport for Model A&#39;</span><span class="p">,</span>
    <span class="n">origin</span><span class="o">=</span><span class="p">(</span><span class="mi">10</span><span class="p">,</span> <span class="mi">10</span><span class="p">),</span> <span class="n">width</span><span class="o">=</span><span class="mi">150</span><span class="p">,</span> <span class="n">height</span><span class="o">=</span><span class="mi">100</span><span class="p">)</span>

<span class="n">myViewport</span><span class="o">.</span><span class="n">setValues</span><span class="p">(</span><span class="n">displayedObject</span><span class="o">=</span><span class="n">myPart</span><span class="p">)</span>

<span class="n">myViewport</span><span class="o">.</span><span class="n">partDisplay</span><span class="o">.</span><span class="n">setValues</span><span class="p">(</span><span class="n">renderStyle</span><span class="o">=</span><span class="n">SHADED</span><span class="p">)</span>
</pre></div>
</div>
</section>
<section id="how-does-the-script-work">
<h2>How does the script work?<a class="headerlink" href="#how-does-the-script-work" title="此标题的永久链接"></a></h2>
<p>This section explains each portion of the example script.</p>
<div class="highlight-python2 notranslate"><div class="highlight"><pre><span></span><span class="kn">from</span> <span class="nn">abaqus</span> <span class="kn">import</span> <span class="o">*</span>
</pre></div>
</div>
<p>This statement makes the basic Abaqus objects accessible to the script. It also provides access to a default model database using the variable named mdb. The statement, <code class="docutils literal notranslate"><span class="pre">from</span> <span class="pre">abaqusConstants</span> <span class="pre">import</span> <span class="pre">*</span></code>, makes the Symbolic Constants defined by the Abaqus Scripting Interface available to the script.</p>
<div class="highlight-python2 notranslate"><div class="highlight"><pre><span></span><span class="kn">import</span> <span class="nn">sketch</span>
<span class="kn">import</span> <span class="nn">part</span>
</pre></div>
</div>
<p>These statements provide access to the objects related to sketches and parts. sketch and part are called Python modules.</p>
<p>The next statement in the script is shown in <a class="hxr-hoverxref hxr-tooltip reference internal" href="#cmd-righttoleft-nls"><span class="std std-numref">图 6</span></a>. You can read this statement from right to left as follows:</p>
<ol class="arabic simple">
<li><p>Create a new model named Model A.</p></li>
<li><p>Store the new model in the model database mdb.</p></li>
<li><p>Assign the new model to a variable called myModel.</p></li>
</ol>
<figure class="align-center" id="id2">
<span id="cmd-righttoleft-nls"></span><a class="reference internal image-reference" href="../../../_images/cmd-righttoleft-nls.png"><img alt="../../../_images/cmd-righttoleft-nls.png" src="../../../_images/cmd-righttoleft-nls.png" style="width: 50%;" /></a>
<figcaption>
<p><span class="caption-number">图 6 </span><span class="caption-text">Creating a new model.</span><a class="headerlink" href="#id2" title="此图像的永久链接"></a></p>
</figcaption>
</figure>
<div class="highlight-python2 notranslate"><div class="highlight"><pre><span></span><span class="n">mySketch</span> <span class="o">=</span> <span class="n">myModel</span><span class="o">.</span><span class="n">ConstrainedSketch</span><span class="p">(</span><span class="n">name</span><span class="o">=</span><span class="s1">&#39;Sketch A&#39;</span><span class="p">,</span> <span class="n">sheetSize</span><span class="o">=</span><span class="mf">200.0</span><span class="p">)</span>
</pre></div>
</div>
<p>This statement creates a new sketch object named Sketch A in myModel. The variable mySketch is assigned to the new sketch. The sketch will be placed on a sheet 200 units square. Note the following:</p>
<ul class="simple">
<li><p>A command that creates something (an &quot;object&quot; in object-oriented programming terms) is called a constructor and starts with an uppercase character. You have seen the Model and Sketch commands that create Model objects and Sketch objects, respectively.</p></li>
<li><p>The command uses the variable myModel that we created in the previous statement. Using variables with meaningful names in a script makes the script easier to read and understand.</p></li>
</ul>
<div class="highlight-python2 notranslate"><div class="highlight"><pre><span></span><span class="n">xyCoordsInner</span> <span class="o">=</span> <span class="p">((</span><span class="o">-</span><span class="mi">5</span> <span class="p">,</span> <span class="mi">20</span><span class="p">),</span> <span class="p">(</span><span class="mi">5</span><span class="p">,</span> <span class="mi">20</span><span class="p">),</span> <span class="p">(</span><span class="mi">15</span><span class="p">,</span> <span class="mi">0</span><span class="p">),</span>
    <span class="p">(</span><span class="o">-</span><span class="mi">15</span><span class="p">,</span> <span class="mi">0</span><span class="p">),</span> <span class="p">(</span><span class="o">-</span><span class="mi">5</span><span class="p">,</span> <span class="mi">20</span><span class="p">))</span>

<span class="n">xyCoordsOuter</span> <span class="o">=</span> <span class="p">((</span><span class="o">-</span><span class="mi">10</span><span class="p">,</span> <span class="mi">30</span><span class="p">),</span> <span class="p">(</span><span class="mi">10</span><span class="p">,</span> <span class="mi">30</span><span class="p">),</span> <span class="p">(</span><span class="mi">40</span><span class="p">,</span> <span class="o">-</span><span class="mi">30</span><span class="p">),</span>
    <span class="p">(</span><span class="mi">30</span><span class="p">,</span> <span class="o">-</span><span class="mi">30</span><span class="p">),</span> <span class="p">(</span><span class="mi">20</span><span class="p">,</span> <span class="o">-</span><span class="mi">10</span><span class="p">),</span> <span class="p">(</span><span class="o">-</span><span class="mi">20</span><span class="p">,</span> <span class="o">-</span><span class="mi">10</span><span class="p">),</span>
    <span class="p">(</span><span class="o">-</span><span class="mi">30</span><span class="p">,</span> <span class="o">-</span><span class="mi">30</span><span class="p">),</span> <span class="p">(</span><span class="o">-</span><span class="mi">40</span><span class="p">,</span> <span class="o">-</span><span class="mi">30</span><span class="p">),</span> <span class="p">(</span><span class="o">-</span><span class="mi">10</span><span class="p">,</span> <span class="mi">30</span><span class="p">))</span>
</pre></div>
</div>
<p>These two statements define the X- and Y-coordinates of the vertices that form the inner and outer profile of the letter A. The variable xyCoordsInner refers to the vertices of the inner profile, and the variable xyCoordsOuter refers to the vertices of the outer profile.</p>
<div class="highlight-python2 notranslate"><div class="highlight"><pre><span></span><span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="nb">len</span><span class="p">(</span><span class="n">xyCoordsInner</span><span class="p">)</span><span class="o">-</span><span class="mi">1</span><span class="p">):</span>
    <span class="n">mySketch</span><span class="o">.</span><span class="n">Line</span><span class="p">(</span><span class="n">point1</span><span class="o">=</span><span class="n">xyCoordsInner</span><span class="p">[</span><span class="n">i</span><span class="p">],</span>
        <span class="n">point2</span><span class="o">=</span><span class="n">xyCoordsInner</span><span class="p">[</span><span class="n">i</span><span class="o">+</span><span class="mi">1</span><span class="p">])</span>
</pre></div>
</div>
<p>This loop creates the inner profile of the letter A in mySketch. Four lines are created using the X- and Y-coordinates of the vertices in xyCoordsInner to define the beginning point and the end point of each line. Note the following:</p>
<ul class="simple">
<li><p>Python uses only indentation to signify the start and the end of a loop. Python does not use the brackets {} of C and C++.</p></li>
<li><p>The <code class="docutils literal notranslate"><span class="pre">len()</span></code> function returns the number of coordinate pairs in xyCoordsInner—five in our example.</p></li>
<li><p>The <code class="docutils literal notranslate"><span class="pre">range()</span></code> function returns a sequence of integers. In Python, as in C and C++, the index of an array starts at zero. In our example range(4) returns 0,1,2,3. For each iteration of the loop in the example the variable i is assigned to the next value in the sequence of integers.</p></li>
</ul>
<p>Similarly, a second loop creates the outer profile of the A character.</p>
<div class="highlight-python2 notranslate"><div class="highlight"><pre><span></span><span class="n">myPart</span> <span class="o">=</span> <span class="n">myModel</span><span class="o">.</span><span class="n">Part</span><span class="p">(</span><span class="n">name</span><span class="o">=</span><span class="s1">&#39;Part A&#39;</span><span class="p">,</span>
    <span class="n">dimensionality</span><span class="o">=</span><span class="n">THREE_D</span><span class="p">,</span> <span class="nb">type</span><span class="o">=</span><span class="n">DEFORMABLE_BODY</span><span class="p">)</span>
</pre></div>
</div>
<p>This statement creates a three-dimensional, deformable part named Part A in myModel. The new part is assigned to the variable myPart.</p>
<div class="highlight-python2 notranslate"><div class="highlight"><pre><span></span><span class="n">myPart</span><span class="o">.</span><span class="n">BaseSolidExtrude</span><span class="p">(</span><span class="n">sketch</span><span class="o">=</span><span class="n">mySketch</span><span class="p">,</span> <span class="n">depth</span><span class="o">=</span><span class="mf">20.0</span><span class="p">)</span>
</pre></div>
</div>
<p>This statement creates a base solid extrude feature in myPart by extruding mySketch through a depth of 20.0.</p>
<div class="highlight-python2 notranslate"><div class="highlight"><pre><span></span><span class="n">myViewport</span> <span class="o">=</span> <span class="n">session</span><span class="o">.</span><span class="n">Viewport</span><span class="p">(</span><span class="n">name</span><span class="o">=</span><span class="s1">&#39;Viewport for Model A&#39;</span><span class="p">,</span>
    <span class="n">origin</span><span class="o">=</span><span class="p">(</span><span class="mi">20</span><span class="p">,</span><span class="mi">20</span><span class="p">),</span> <span class="n">width</span><span class="o">=</span><span class="mi">150</span><span class="p">,</span> <span class="n">height</span><span class="o">=</span><span class="mi">100</span><span class="p">)</span>
</pre></div>
</div>
<p>This statement creates a new viewport named Viewport for Model A in session. The new viewport is assigned to the variable myViewport. The origin of the viewport is at (20, 20), and it has a width of 150 and a height of 100.</p>
<div class="highlight-python2 notranslate"><div class="highlight"><pre><span></span><span class="n">myViewport</span><span class="o">.</span><span class="n">setValues</span><span class="p">(</span><span class="n">displayedObject</span><span class="o">=</span><span class="n">myPart</span><span class="p">)</span>
</pre></div>
</div>
<p>This statement tells Abaqus to display the new part, myPart, in the new viewport, myViewport.</p>
<div class="highlight-python2 notranslate"><div class="highlight"><pre><span></span><span class="n">myViewport</span><span class="o">.</span><span class="n">partDisplayOptions</span><span class="o">.</span><span class="n">setValues</span><span class="p">(</span><span class="n">renderStyle</span><span class="o">=</span><span class="n">SHADED</span><span class="p">)</span>
</pre></div>
</div>
<p>This statement sets the render style of the part display options in myViewport to shaded. As a result, myPart appears in the shaded render style.</p>
</section>
</section>


           </div>
          </div>
          <footer><div class="rst-footer-buttons" role="navigation" aria-label="页脚">
        <a href="index.html" class="btn btn-neutral float-left" title="Simple examples" accesskey="p" rel="prev"><span class="fa fa-arrow-circle-left" aria-hidden="true"></span> 上一页</a>
        <a href="read-output.html" class="btn btn-neutral float-right" title="Reading from an output database" accesskey="n" rel="next">下一页 <span class="fa fa-arrow-circle-right" aria-hidden="true"></span></a>
    </div>

  <hr/>

  <div role="contentinfo">
    <p>&#169; 版权所有 2022, WANG Hailin.</p>
  </div>

  利用 <a href="https://www.sphinx-doc.org/">Sphinx</a> 构建，使用的 
    <a href="https://github.com/readthedocs/sphinx_rtd_theme">主题</a>
    由 <a href="https://readthedocs.org">Read the Docs</a> 开发.
   

</footer>
        </div>
      </div>
    </section>
  </div>
   
<div
  class="rst-versions"
  data-toggle="rst-versions"
  role="note"
  aria-label="versions"
>
  <span class="rst-current-version" data-toggle="rst-current-version">
    <span class="fa fa-book"> Read the Docs</span>
    v: 2016
    <span class="fa fa-caret-down"></span>
  </span>
  <div class="rst-other-versions">
    
    <dl>
      <dt>Languages</dt>
       
        <dd><a href="/abqpy/en/2016/">English</a></dd>
          
      <strong>
        
        <dd><a href="/abqpy/zh_CN/2016/">简体中文</a></dd>
        
      </strong>
       
    </dl>
     
    <dl>
      <dt>版本</dt>
       
        <dd><a href="/abqpy/zh_CN/2023/">2023</a></dd>
          
        <dd><a href="/abqpy/zh_CN/2022/">2022</a></dd>
          
        <dd><a href="/abqpy/zh_CN/2021/">2021</a></dd>
          
        <dd><a href="/abqpy/zh_CN/2020/">2020</a></dd>
          
        <dd><a href="/abqpy/zh_CN/2019/">2019</a></dd>
          
        <dd><a href="/abqpy/zh_CN/2018/">2018</a></dd>
          
        <dd><a href="/abqpy/zh_CN/2017/">2017</a></dd>
          
      <strong>
        
        <dd><a href="/abqpy/zh_CN/2016/">2016</a></dd>
        
      </strong>
        
        <dd><a href="/abqpy/zh_CN/latest/">latest</a></dd>
          
        <dd><a href="/abqpy/zh_CN/sphinx-book-theme/">sphinx-book-theme</a></dd>
          
        <dd><a href="/abqpy/zh_CN/furo/">furo</a></dd>
         
    </dl>
     
    <dl>
      <dt>下载</dt>
      
      <dd><a href="/abqpy/zh_CN/2016/abqpy-docs-zh_CN-2016.pdf">pdf</a></dd>
      
      <dd><a href="/abqpy/zh_CN/2016/abqpy-docs-zh_CN-2016.epub">epub</a></dd>
      
    </dl>
     
    <hr />
    <a
      href="https://tech.michaelaltfield.net/2020/07/18/sphinx-rtd-github-pages-1/"
      >Continuous Documentation</a
    >
    hosting provided by <a href="https://pages.github.com/">GitHub Pages</a>.
  </div>
</div>
<script>
      jQuery(function () {
          SphinxRtdTheme.Navigation.enable(true);
      });
  </script> 

</body>
</html>